//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalPROJECT_S2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAPIFoootballDataEntities : DbContext
    {
        public MyAPIFoootballDataEntities()
            : base("name=MyAPIFoootballDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<Standing> Standings { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
